### ISSUE TITLE
Versioning of this Tests Repo

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5-tests#10]
In general my idea would be this repo follows the branch/tag names of [html-tidy5](https://github.com/htacg/tidy-html5)...

That is -

 1. The `master` branch be the last **release**
 2. The `next` branch is the last compatible version
 3. Special branches, can be used for testing development

That means, at this moment, the `master` stays at 5.4.0... the last official release...

As soon as PR [#514](https://github.com/htacg/tidy-html5/pull/514) is triggered, either a `next` branch is created from `custom_tags`, or indeed `custom_tags` is **renamed** to `next`, and this becomes the default clone.

So let's say we end up with a merged 5.5.7, then that is the version tagged to `next`... Now while subsequent version bumps, 5.5.8, 5.5.9, may not mean any change in the `tests` **expectes**... you get a clean diff... ie no diff... tests will stay at 5.5.7... that is the last compatible version.

The idea here is that a developer can build a new version of Tidy 5.5.nn[.rc], and can run a full regression test, as part of the final, successful build is done... it should only take seconds, and be part of every build...

Make it usable, and easy to `test`, lots of things, quickly, fun,... 

Look forward to feedback... thanks...

**Comment by balthisar** [comment]
Agreed completely, @geoffmcl.

**Comment by geoffmcl** [comment]
Have now created, and set `next` as the default...

Should later delete `custom_tags` branch, but that can wait...

**Comment by balthisar** [comment]
> Should later delete custom_tags branch, but that can wait

Deleted, and closed!
