### ISSUE TITLE
Access Tests need some TLC

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5-tests#11]
While the initial part of the testing `-c access` runs no problem, the diff between `expects` and `results` needs an update...

The common, acceptable diffs are -

```diff
- Accessibility Checks: Version 0.1
+Accessibility Checks:
 and warning messages like
-1 warning, 0 errors were found!
+Tidy found 1 warning and 0 errors!
 and the various other info blah, blah, blah
```

I propose that `--show-info no` be added to these tests, since they are nothing about this `Info:` output... None of that output contributes to the test being conducted... just added to `_onetesta.bat`...

And remove the impossible for diff option `--gnu-emacs yes` - that leads to an automatic difference between Windows and unix/Mac! Not sure how it got in `_onetesta.bat` in the first place... did I do that?

Then the diff becomes manageable... some 122 differences, in 119 tests... 

A few **need** to be examined, to really question some of the warning differences... but most look good for an update of the base...

Will study more about any questionable differences...

Feedback, and help much appreciated... thanks...

**Comment by geoffmcl** [comment]
Of the 122 diffs, **eliminate** all those that have no change in the `access` messages, reduces us to just ten(10) cases that need to be examined closer -

 1. case-11_2_1_4.html case-11_2_1_4.txt
 2. case-2_2_1_1.txt
 3. case-2_2_1_2.txt
 4. case-2_2_1_3.txt
 5. case-2_2_1_4.txt
 6. case-3_6_1_1.html case-3_6_1_1.txt
 7. case-3_6_1_2.html case-3_6_1_2.txt
 8. case-3_6_1_4.html case-3_6_1_4.txt
 9. case-6_5_1_4.txt
 10. case-7_2_1_1.txt

#### 11_2_1_4
 
This `11_2_1_4` case is a simple input, `<dir>Hello</dir>`. 5.2 would output `<div style="margin-left: 2em">Hello</div>`

However, from 5.4 onwards, thus in `next`, will output `<ul>Hellow</ul>`... This is a `HTML 4.0 Transitional` document. Does this rise to the level of a **regression** in tidy code? Or can this be accepted as equivalent? That is we just update the `expects`? Or restore previous output?
 
The essentual parts of the diff:

```diff
-line 8 column 6 - Warning: missing <li>
 
-Accessibility Checks: Version 0.1
+Accessibility Checks:
 
-line 8 column 6 - Access: [6.1.1.3]: style sheets require testing (style attribute).
+line 1 column 1 - Access: [3.3.1.1]: use style sheets to control presentation.
 line 3 column 1 - Access: [13.2.1.1]: Metadata missing.
 line 8 column 1 - Access: [11.2.1.4]: replace deprecated html <dir>.
-line 8 column 6 - Access: [3.6.1.4]: list usage invalid <li>.
-line 8 column 1 - Warning: replacing obsolete element <dir> by <ul>
-Info: Doctype given is "-//W3C//DTD HTML 4.0 Transitional//EN"
-Info: Document content looks like HTML 4.01 Transitional
-2 warnings, 0 errors were found!
+line 8 column 1 - Warning: replacing obsolete element <dir> with <ul>
+Tidy found 1 warning and 0 errors!
```

Note the additional warning, was 2 now 1, and some changes in the Access: values output, but maybe this is ok.

Need help, feedback to decide... thanks...

#### 2_2_1_1, 2, 3, 4

Essentually only outputs two(2) additional `access` messages, which look reasonable - the second is bumped to 2, 3, and 4 resp.

```diff
+line 3 column 1 - Access: [13.2.1.1]: Metadata missing.
+line 6 column 1 - Access: [2.2.1.1]: poor color contrast (text).
```

Think they should be update, unless I am missing something else here...

#### 3_6_1_1, 2

These 2 are similar to `11_2_1_4`, where the use of `<div style="margin-left: 2em">...</div>` has been replaced with a `<ul>...</ul>`... so I guess their fate depend on the decision for the first...

#### 3_6_1_4

This changes dramatically from 5 warnings to none! 

```diff
-line 7 column 1 - Warning: <li> isn't allowed in <body> elements
-line 6 column 1 - Info: <body> previously mentioned
-line 7 column 1 - Warning: inserting implicit <ul>
-line 8 column 1 - Warning: discarding unexpected </body>
-line 9 column 1 - Warning: discarding unexpected </html>
-line 7 column 1 - Warning: missing </ul>
```

But here I think the current output is **right**. It almost seems this `expects` has been very wrong from an earlier time...

Quite strange? How did this happen? When did this bogus message output get added? Why?

If cleared of problems, should be an update of `expects`...

#### 6_5_1_4

Now has some additional `access` message output... If these are correct, then just an update...

#### 7_2_1_1

Now the warning comes after the `accessibility` checks... Not sure when we changed the order of when such warnings are emitted...

It is the same warnings, so maybe no problem here... update?

### Choices

As indicated would appreciate some help, feedback, on what is the correct choice in each of these `cases`... thanks...

**Comment by geoffmcl** [comment]
Oops, just push fixes to `_onetesta.bat` but accidentally added issue #8 to it... drat...

The fix was to remove the option `--gnu-emacs yes`, which would cause a problem between Windows and Unix/Mac file names, and added `--show-info no`, so we just see the main warning/error information...

Hope someone gets some time to cast an eye over the above 10 differences... and help make a choice... thanks...

**Comment by balthisar** [comment]
@geoffmcl, I agree with `show-info: no` in all cases; this extra information doesn't really affect what Tidy _does_, and slight changes just make it more difficult to manage in the future.

I think that in all cases where we think Tidy's output is correct now, we should update the expects. I think no one has looked at accesstests in a long time with the emphasis on testbase. If there's a regression, but the output is correct, then update away.

**Comment by geoffmcl** [comment]
@balthisar well looking again and again at the differences, I think the latest are **all** correct, so have updated `expects` accordingly...

Anyway, I have documented the 10 cases where there could be some doubt, so will let any of these come up as a **new** issue, if there is a problem...

Now get a 100% equal using tidy 5.5.7, and still no change for 5.5.10, so things are looking good here...

So far have only worked on the `tools-cmd`... hope you or others will find time to test with `tools-sh`...

Have started some **fixes** for https://github.com/htacg/tidy-html5/issues/338, so think this can be closed...
