### ISSUE TITLE
Some legacy doc output errors in regression tests

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5-tests#15]
Recently ran into `regression` testing problems, in that my **fix** for [Issue 461/531](https://github.com/htacg/tidy-html5/pull/531) caused quite a number of **diffs**, and some exit value changes... Arrgh!!!

On investigating this, it seems some **errors** have crept into the `regression` tests!

Now most of the `regression` tests are still **legacy** documents. Take say 1086083. It is `HTML 4.01`, and testcase contains the code `<li>Huh?</li>`, and tidy is supposed to **fix** this by adding a `<ul>`, which, if we back up the tidy-tests repo that is what we will find in the original `master` branch, `out_1086083.html`, but **not** in the current `next` branch `expects/case-1086083.html`!

In other words, this `expects/case-1086083.html` now **fails** validation with the error `Line 16, Column 6: document type does not allow element "LI" here; missing one of "UL", "OL" start-tag`! While the original `out_1086083.html` **PASSES**!!

That is we now expect, allow some html5 tolerance in a legacy document, and this is an error! And there seems to be several other similar cases... yet to be explored fully...

So far the differences and or exit `regression` errors seem to be in the following tests -

```
1086083.html 1086083.txt
1316307b.html 1316307b.txt
1331849.html 1331849.txt
1423252.html 1423252.txt
435917.html 435917.txt 
487204.html 487204.txt 
836462a.html 836462a.txt
836462b.html 836462b.txt
836462c.html 836462c.txt
```

Any assistance investigating and correcting these would be most appreciated... thanks...

**Comment by geoffmcl** [comment]
Ongoing research into this issue -

First, all 9 cases were passed to the W3C validator, using the `master` `out_XXXXX.html` file. All **passed** except **435917**. This may in fact indicate an ongoing **bug** in tidy, in that it output a `<form>` without an `action` attribute. But that should be a separate `tidy` issue...

Then all 9 cases were passed to the W3C validator, using the `next` `case-XXXXX.html` expects file. Interestingly, all cases **failed** with 1 or more errors, except **435917**! This particular case does need to be looked at more closely. But this indicates each of these cases **need** to be restored to the former expected outputs, if the patch in my [Issue-461](https://github.com/htacg/tidy-html5/tree/issue-461) branch is used...

In detail the **results** were, case by case - wow, what a **lot** of manual clicking, copy and paste, time... -

 1. case-1086083.html - 1 Error: 
    - Line 16, Column 6: document type does not allow element "LI" here; missing one of "UL", "OL" start-tag  `<li>Huh?</li>`
 
 2. case-1316307b.html - 2 Errors: 
    - Line 8, Column 8: document type does not allow element "TD" here `<td>Cell Data</td>`, and 
    - Line 9, Column 7: end tag for "UL" which is not finished `</ul>`
 
 3. case-1331849.html - 2 Errors: 
    - Line 8, Column 6: document type does not allow element "TR" here `<tr>`, and  
    - Line 13, Column 6: document type does not allow element "TR" here `<tr>`
 
 4. case-1423252.html - 2 Errors: 
    - Line 11, Column 4: document type does not allow element "DT" here; assuming missing "DL" start-tag `<dt><font color="red">c</font></dt>`, and 
    - Line 12, Column 7: end tag for "DL" omitted, but its declaration does not permit this `</body>`
 
 5. case-435917.html - PASSED!!!
 
 6. case-487204.html - 1 Error: 
    - Line 14, Column 19: start tag for "LI" omitted, but its declaration does not permit this `<ol class='c1'>`
 
 7. case-836462a.html - 1 Error: 
    - Line 18, Column 8: document type does not allow element "UL" here; assuming missing "LI" start-tag `<ul>`
 
 8. case-836462b.html - 1 Error: 
    - Line 18, Column 8: document type does not allow element "UL" here; assuming missing "LI" start-tag `<ul>`

 9. case-836462c.html - 2 Errors: 
    - Line 10, Column 10: document type does not allow element "br" here; assuming missing "li" start-tag `<br />`, and 
    - Line 11, Column 7: end tag for "li" omitted, but OMITTAG NO was specified `</ol>`

Case 5 - 435917 - is indeed strange. It seems to test that `<input onfocus"x()">` should report an `unknown` attribute - but the expected `msg` text has `line 10 column 1 - Warning: <input> attribute with missing trailing quote mark`, which is not quite the same thing, but close I suppose. But certainly the `next` expects omits adding the implied `<form>`, which I think is ok in html5, but not in html4, maybe, since the validator does not seem to agree... But as stated, this particular test case needs to be more fully explored, and understood... separately...

In time I will try to push an `issue-15` branch, with these changes implemented... such that my Tidy `issue-461` fully passes...

Meantime, seek further comment and feedback on this issue... thanks...

**Comment by balthisar** [comment]
Confirmed while testing `issue-461`; I didn't step through it line by line, but agree to updating testbase after merging #540 (including case-by-case fixes, if applicable).

**Comment by geoffmcl** [comment]
@balthisar you should be able to now check out `issue-461` here, and it should **pass** 100%

It does for me in Windows...

Hope you and @lhchavez get a chance to test this... thanks...

**Comment by balthisar** [comment]
@geoffmcl, yup, confirmed, no diffs with this branch.

**Comment by geoffmcl** [comment]
Seems this has been solved, so closing...
