### ISSUE TITLE
Being able to test other than the 'testbase' set in unix!

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5-tests#4]
In Windows, with the addition of the handling of `PROCESS_CLI` in **tools-cmd/_environmnet.bat**, it is possible to set the following parameters for the tests -

```
 alltest [-t [path/to/]tidy[.exe]] [-o output_directory] [-c case_set_name]
```

Accordingly, to further facilitate re-testing of the `specials`, added a `_manifest.txt`, and added a `special-expects`, with the expected results. And the tests ran well in Windows... and **passed**...

But it seems that `CLI` has not yet been added to the **tools-sh**, so it does not seem possible to run the **specials** set in unix, without directly modifying the scripts, or creating new scripts, but maybe I missed something...

This would also apply to doing some re-testing of the `unknown` folder... and say creating a **new** folder, to pre-test a test, before adding it to the `testbase`...

Is this CLI capability going to be added to **tools-sh**? Or is there another way?

**Comment by geoffmcl** [comment]
Ok, using the `testxml.sh` model, copied it to a `testspl.sh`, and made the appropriate modification, and got the **special** tests to run...

As expected, the compare of the `expects` and `results` **failed**! That is the reason they were moved to 'special' in the first place... but now I can work on a solution as time permits...

But it would still be nice if this could be all within **testall.sh**, then even `testxml.sh` would not be needed... and maybe the functionality of `run-tests.sh` could be also be folded into `testall.sh` there by removing it also...

**Comment by geoffmcl** [comment]
PS: Pushed my `testapl.sh` in case others want to try ;=))

**Comment by balthisar** [comment]
I'll have a try. I also plan to rework the Unix scripts, but wanted to get the Windows batch scripts cleaned up first. I see you've done quite a bit of work cleaning them. If you're generally happy with them then I'll go back to the shell scripts.

**Comment by balthisar** [comment]
I'll close this because at some point I must have updated the Unix tool to use TY_CASES_SETNAME, and it works when I set it to special with `export TY_CASES_SETNAME=special`
