### ISSUE TITLE
Update to 5.2.0 for clean RT run in all OSES

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5-tests#5]
A number of tests require an update to **pass** with release 5.2.0

Read [Issue #390](https://github.com/htacg/tidy-html5/issues/390#issuecomment-205372993)...

These tests output html better indented, so need updating...
- testbase:  427820, 504206, 505770
- xml:         1510101!

**Comment by balthisar** [comment]
I'll close this issue, as we've release 5.4 now.
